/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-basic-sky-b2a4fd1b92c248abaae31975c9ea79e2
Title: FREE - SkyBox Basic Sky
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import skyScene from "../assets/models/3D/skyy.glb";
const Sky = (props) => {
  const { nodes, materials } = useGLTF(skyScene);
  return (
    <group {...props} dispose={null}>
      <group scale={80}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere__0.geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload(skyScene);

export default Sky;
